name: Release to Docker Registries
on:
  repository_dispatch:
    types: [image-built]

jobs:
  release-google:
    runs-on: ubuntu-latest
    steps:
      - name: Publish release to europe-docker.pkg.dev/flownative/docker
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ github.event.client_payload.image_tag }}
          tag_latest: 'yes'

          source_image_name: ${{ github.event.client_payload.image_name }}
          source_registry_username: github
          source_registry_password: ${{ secrets.FLOWNATIVE_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: europe-docker.pkg.dev/flownative/docker/beach-php
          target_registry_username: '_json_key'
          target_registry_password: ${{ secrets.GOOGLE_ARTIFACTS_PASSWORD_DOCKER }}
          target_registry_endpoint: https://europe-docker.pkg.dev

  release-dockerio:
    runs-on: ubuntu-latest
    steps:
      - name: Publish release to docker.io
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ github.event.client_payload.image_tag }}
          tag_latest: 'no'

          source_image_name: ${{ github.event.client_payload.image_name }}
          source_registry_username: github
          source_registry_password: ${{ secrets.FLOWNATIVE_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: flownative/beach-php
          target_registry_username: ${{ secrets.DOCKER_IO_REGISTRY_USER }}
          target_registry_password: ${{ secrets.DOCKER_IO_REGISTRY_PASSWORD }}
          target_registry_endpoint: https://index.docker.io/v1/
